# NUMPY (numerical python)

In [34]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [5]:
arr=np.array(l) # converting list into array

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [9]:
np.asarray(l)  # converting into array

array([1, 2, 3, 4, 5])

In [11]:
arr1=np.array([[1,2,3],[4,5,6]])

In [14]:
arr.ndim # dimension of array

1

In [12]:
arr1.ndim  # dimension of array

2

In [13]:
type(arr1)

numpy.ndarray

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
mat=np.matrix(l)   # always have 2d  matrix is always a type of array

In [19]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [20]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [22]:
a=arr  # reassigning the values

In [23]:
a

array([1, 2, 3, 4, 5])

In [24]:
a[0]=100 # reassigning the value at 0 index

In [25]:
arr  # changed the zeroth  index value in a same array 

array([100,   2,   3,   4,   5])

In [26]:
a  # changed the zeroth index value

array([100,   2,   3,   4,   5])

In [31]:
# line no25 and 26 showing swallow copy operation where whenver we change any value in one it also shows in other
# in case of swallow copy they didn't create separate memory for a it is only refering towards arr

In [32]:
a

array([100,   2,   3,   4,   5])

In [33]:
b=np.copy(arr)  # it will create a separeate memory for b 

In [30]:
b

array([100,   2,   3,   4,   5])

In [34]:
b[0]=98 # only 0th index of b changed n0t arr this is because ...it create different memory location for each other.
# deep copy

In [35]:
b

array([98,  2,  3,  4,  5])

In [36]:
arr

array([100,   2,   3,   4,   5])

In [37]:
# multiple function in numpy
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [45]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [46]:
iterable = (i*i for i in range(5))

In [42]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [43]:
np.fromstring('23 43 43 23 45',sep=' ') # separating string with space and returning a list

array([23., 43., 43., 23., 45.])

In [45]:
np.fromstring('34,34,12,54' ,sep=',') # separarting string with comma and returnning a list

array([34., 34., 12., 54.])

In [46]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr.ndim # 1.dimension

1

In [48]:
arr1.ndim

2

In [49]:
arr.size

5

In [50]:
arr1.size

6

In [51]:
arr.shape

(5,)

In [52]:
arr1.shape

(2, 3)

In [53]:
arr.dtype

dtype('int64')

In [54]:
arr1.dtype

dtype('int64')

# LECTURE2

In [55]:
import numpy as np

In [56]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [57]:
list(range(0,9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [59]:
list(range(0.4,10.7))  # range never take floating data type

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(0.4,10.7)  # function in numpy arange take float value

array([ 0.4,  1.4,  2.4,  3.4,  4.4,  5.4,  6.4,  7.4,  8.4,  9.4, 10.4])

In [61]:
list(np.arange(-7,10.4,0.2))  # arange function in numpy also can take fraction of value 

[-7.0,
 -6.8,
 -6.6,
 -6.3999999999999995,
 -6.199999999999999,
 -5.999999999999999,
 -5.799999999999999,
 -5.599999999999999,
 -5.399999999999999,
 -5.199999999999998,
 -4.999999999999998,
 -4.799999999999998,
 -4.599999999999998,
 -4.399999999999998,
 -4.1999999999999975,
 -3.9999999999999973,
 -3.799999999999997,
 -3.599999999999997,
 -3.399999999999997,
 -3.1999999999999966,
 -2.9999999999999964,
 -2.7999999999999963,
 -2.599999999999996,
 -2.399999999999996,
 -2.1999999999999957,
 -1.9999999999999956,
 -1.7999999999999954,
 -1.5999999999999952,
 -1.399999999999995,
 -1.1999999999999948,
 -0.9999999999999947,
 -0.7999999999999945,
 -0.5999999999999943,
 -0.39999999999999414,
 -0.19999999999999396,
 6.217248937900877e-15,
 0.2000000000000064,
 0.4000000000000066,
 0.6000000000000068,
 0.8000000000000069,
 1.000000000000007,
 1.2000000000000064,
 1.4000000000000075,
 1.6000000000000085,
 1.8000000000000078,
 2.000000000000007,
 2.200000000000008,
 2.4000000000000092,
 2.6000000000000

In [63]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [64]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [65]:
np.logspace(1,5,20, base=2)

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [66]:
np.zeros(5)  # it is a functio which create arrays in the form of zeros

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4))  # generating arr with 3 rows and 4  columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))  # generating  3 arrays with 4 rows and 2 columns

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [47]:
arr3=np.zeros((3,4,2,3))

In [50]:
arr3

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [48]:
arr3.ndim

4

In [49]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
arr = np.ones((3,4))

In [5]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr +5  # adding 5 with every element of the array

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [8]:
arr*6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [9]:
np.empty((3,5))

array([[4.65367768e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.90791977e-310]])

In [11]:
arr1=np.eye(5)   #always return square matrixes with 1 in diagonal

In [12]:
import pandas as pd

In [13]:
pd.DataFrame(arr1)   # any arrays and matrix can be represent as a dataframe

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [14]:
np.random.rand(2,3) # give dataset where  mean and std can be anything

array([[0.30491543, 0.70002804, 0.05562013],
       [0.51592282, 0.15680092, 0.81306178]])

In [15]:
np.random.randn(7,3) # giving dataset with standard normal deviation means mean is 0 and std=1

array([[-1.34775313, -1.3548795 ,  0.57486727],
       [ 0.97259163,  0.28784878,  0.78619602],
       [-0.12428773, -0.32118527, -0.20700366],
       [ 0.39822962, -0.59174991,  0.83091382],
       [ 0.96063319, -0.51211647,  0.94650701],
       [ 0.79464239,  0.57380833,  0.23789248],
       [ 0.45018442, -0.57625361, -0.63344544]])

In [17]:
arr2=np.random.randint(1,5, (3,4)) # generating data with 1 to 4 range with 3 rows and 4 columns

In [18]:
arr2

array([[3, 3, 3, 1],
       [1, 1, 2, 1],
       [2, 2, 3, 2]])

In [19]:
arr2.size

12

In [20]:
arr2.shape

(3, 4)

In [22]:
arr2.reshape(6,2) # during reshaping data one thing is in mind that size reamin same like 4*3,6*2

array([[3, 3],
       [3, 1],
       [1, 1],
       [2, 1],
       [2, 2],
       [3, 2]])

In [23]:
arr2.reshape(3,2)  # no equal size as 4*3 arr

ValueError: cannot reshape array of size 12 into shape (3,2)

In [24]:
arr2.reshape(12,1)

array([[3],
       [3],
       [3],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [3],
       [2]])

In [25]:
arr2.reshape(-4,3)

array([[3, 3, 3],
       [1, 1, 1],
       [2, 1, 2],
       [2, 3, 2]])

In [26]:
arr2.reshape(2,2,3) # converting into 3 dimension 3 square bracket in last and begining

array([[[3, 3, 3],
        [1, 1, 1]],

       [[2, 1, 2],
        [2, 3, 2]]])

In [28]:
arr2.reshape(2,2,3).ndim

3

In [29]:
arr2.ndim

2

In [32]:
arr2.reshape(2,2,3,1,1,1)   # 6 dimension 

array([[[[[[3]]],


         [[[3]]],


         [[[3]]]],



        [[[[1]]],


         [[[1]]],


         [[[1]]]]],




       [[[[[2]]],


         [[[1]]],


         [[[2]]]],



        [[[[2]]],


         [[[3]]],


         [[[2]]]]]])

In [33]:
arr2.reshape(3,2,1,1)

ValueError: cannot reshape array of size 12 into shape (3,2,1,1)

In [36]:
arr2.reshape(2,2,3,1,1)  # 5 dimension

array([[[[[3]],

         [[3]],

         [[3]]],


        [[[1]],

         [[1]],

         [[1]]]],



       [[[[2]],

         [[1]],

         [[2]]],


        [[[2]],

         [[3]],

         [[2]]]]])

In [37]:
(arr2.reshape(2,2,3,1,1)).ndim  # 5 dimension

5

In [39]:
arr1=np.random.randint(1,10,(5,6))

In [52]:
arr1

array([[ 2,  2],
       [15,  7]])

In [53]:
arr1>8 # filter out the data which is greater then 8

array([[False, False],
       [ True, False]])

In [42]:
arr1>5  # filter out the data which is greater than 5

array([[False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False,  True,  True, False,  True,  True],
       [ True, False,  True,  True,  True,  True]])

In [45]:
arr1[arr1>8]  # filter out data  which is greater than 8 from matrix and give it to you

array([9])

In [46]:
arr1[arr1>4] # filter out the data which is greater than 5  and give it to you

array([5, 7, 5, 6, 7, 7, 7, 6, 7, 7, 6, 6, 9])

In [63]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [64]:
arr1[0]

array([2, 1, 1])

In [65]:
arr1[0,[0,1]] # extracting data from matries

array([2, 1])

In [54]:
arr1[2,[2,3]]

array([1, 4])

In [54]:
arr1 = np.random.randint(1,3, (3,3,))
arr2 = np.random.randint(1,3, (3,3))

In [55]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [56]:
arr2

array([[2, 2, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [57]:
arr1+arr2

array([[4, 3, 2],
       [3, 2, 3],
       [2, 3, 2]])

In [58]:
arr1-arr2

array([[ 0, -1,  0],
       [ 1,  0, -1],
       [ 0, -1,  0]])

In [59]:
arr1*arr2  # it gives index wise multiplication

array([[4, 2, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [60]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [2. , 1. , 0.5],
       [1. , 0.5, 1. ]])

In [61]:
arr1@arr2  # matrix multiplication

array([[6, 7, 5],
       [6, 7, 5],
       [4, 5, 4]])

In [62]:
arr1/0

/tmp/ipykernel_84/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [65]:
# numpy------broadcasting
arr=np.zeros((2,3))

In [66]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
arr+3

array([[3., 3., 3.],
       [3., 3., 3.]])

In [68]:
a=np.array([1,2,3,4])

In [69]:
arr+a

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [70]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356]])

In [71]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.     , 0.30103, 0.30103]])

In [74]:
np.mean(arr1)

1.7777777777777777

In [75]:
np.median(arr1)

2.0

In [80]:
from scipy import stats
stats.mode(arr1)

/tmp/ipykernel_78/637220780.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(arr1)


ModeResult(mode=array([[2, 2, 2]]), count=array([[2, 2, 3]]))

In [81]:
np.min(arr1)

1

In [82]:
np.max(arr1)

2

In [83]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

LECTURE3

In [1]:
import numpy as np

In [3]:
# Numpy -- array manipulation
arr = np.random.randint(1,10, (4,4))


In [5]:
arr

array([[5, 3, 3, 1],
       [6, 6, 6, 9],
       [2, 5, 8, 2],
       [6, 9, 5, 9]])

In [6]:
arr.reshape(8,2)

array([[5, 3],
       [3, 1],
       [6, 6],
       [6, 9],
       [2, 5],
       [8, 2],
       [6, 9],
       [5, 9]])

In [7]:
arr.T  #  for transposing the columnn into rows


array([[5, 6, 2, 6],
       [3, 6, 5, 9],
       [3, 6, 8, 5],
       [1, 9, 2, 9]])

In [9]:
arr.flatten() #  here it is converting the 2d array into 1 d array

array([5, 3, 3, 1, 6, 6, 6, 9, 2, 5, 8, 2, 6, 9, 5, 9])

In [10]:
arr

array([[5, 3, 3, 1],
       [6, 6, 6, 9],
       [2, 5, 8, 2],
       [6, 9, 5, 9]])

In [13]:
np.expand_dims(arr,axis=1)  # expanding the dimension from 2d to 3d

array([[[5, 3, 3, 1]],

       [[6, 6, 6, 9]],

       [[2, 5, 8, 2]],

       [[6, 9, 5, 9]]])

In [14]:
np.expand_dims(arr,axis=0)

array([[[5, 3, 3, 1],
        [6, 6, 6, 9],
        [2, 5, 8, 2],
        [6, 9, 5, 9]]])

In [15]:
data = np.array([[1],[2],[3]])

In [16]:
data

array([[1],
       [2],
       [3]])

In [17]:
np.repeat(data,4)  # repeating every data 4 times and returning

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [19]:
np.roll(data,2)  # rolliing the data 

array([[2],
       [3],
       [1]])

In [20]:
np.diag(np.array([1,2,3,4]))  # inserting no in the diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
# numpy --binary operators

In [3]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [4]:
arr1

array([[2, 4, 2, 7],
       [8, 9, 3, 9],
       [8, 1, 6, 5]])

In [5]:
arr1+arr2

array([[10,  9,  6, 13],
       [13, 13,  7, 18],
       [ 9,  5, 13, 11]])

In [6]:
arr1*arr2

array([[16, 20,  8, 42],
       [40, 36, 12, 81],
       [ 8,  4, 42, 30]])

In [7]:
arr1/arr2

array([[0.25      , 0.8       , 0.5       , 1.16666667],
       [1.6       , 2.25      , 0.75      , 1.        ],
       [8.        , 0.25      , 0.85714286, 0.83333333]])

In [8]:
arr1**arr2

array([[      256,      1024,        16,    117649],
       [    32768,      6561,        81, 387420489],
       [        8,         1,    279936,     15625]])

In [9]:
~arr1

array([[ -3,  -5,  -3,  -8],
       [ -9, -10,  -4, -10],
       [ -9,  -2,  -7,  -6]])

In [10]:
arr1

array([[2, 4, 2, 7],
       [8, 9, 3, 9],
       [8, 1, 6, 5]])

In [11]:
import numpy as np

In [14]:
arr1>arr2

array([[False, False, False,  True],
       [ True,  True, False, False],
       [ True, False, False, False]])

In [15]:
#numpy --string functions

In [16]:
arr = np.array(['sudh','kumar'])

In [17]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [18]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [19]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [20]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [21]:
# numpy mathematical function
arr1

array([[2, 4, 2, 7],
       [8, 9, 3, 9],
       [8, 1, 6, 5]])

In [22]:
np.sin(arr1)

array([[ 0.90929743, -0.7568025 ,  0.90929743,  0.6569866 ],
       [ 0.98935825,  0.41211849,  0.14112001,  0.41211849],
       [ 0.98935825,  0.84147098, -0.2794155 , -0.95892427]])

In [23]:
np.cos(arr1)

array([[-0.41614684, -0.65364362, -0.41614684,  0.75390225],
       [-0.14550003, -0.91113026, -0.9899925 , -0.91113026],
       [-0.14550003,  0.54030231,  0.96017029,  0.28366219]])

In [24]:
np.tan(arr1)

array([[-2.18503986,  1.15782128, -2.18503986,  0.87144798],
       [-6.79971146, -0.45231566, -0.14254654, -0.45231566],
       [-6.79971146,  1.55740772, -0.29100619, -3.38051501]])

In [25]:
np.log10(arr1)

array([[0.30103   , 0.60205999, 0.30103   , 0.84509804],
       [0.90308999, 0.95424251, 0.47712125, 0.95424251],
       [0.90308999, 0.        , 0.77815125, 0.69897   ]])

In [26]:
np.exp(arr1)

array([[7.38905610e+00, 5.45981500e+01, 7.38905610e+00, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.00855369e+01, 8.10308393e+03],
       [2.98095799e+03, 2.71828183e+00, 4.03428793e+02, 1.48413159e+02]])

In [27]:
np.power(arr1,2)

array([[ 4, 16,  4, 49],
       [64, 81,  9, 81],
       [64,  1, 36, 25]])

In [28]:
np.mean(arr1)

5.333333333333333

In [29]:
np.median(arr1)

5.5

In [30]:
np.std(arr1)

2.778888666755511

In [31]:
np.var(arr1)

7.722222222222221

In [32]:
np.min(arr1)

1

In [33]:
np.max(arr1)

9

In [35]:
# numpy --arthimetic operation
arr1

array([[2, 4, 2, 7],
       [8, 9, 3, 9],
       [8, 1, 6, 5]])

In [36]:
arr1-arr2

array([[-6, -1, -2,  1],
       [ 3,  5, -1,  0],
       [ 7, -3, -1, -1]])

In [37]:
np.subtract(arr1,arr2)

array([[-6, -1, -2,  1],
       [ 3,  5, -1,  0],
       [ 7, -3, -1, -1]])

In [38]:
np.multiply(arr1,arr2)

array([[16, 20,  8, 42],
       [40, 36, 12, 81],
       [ 8,  4, 42, 30]])

In [39]:
np.mod(arr1,arr2)

array([[2, 4, 2, 1],
       [3, 1, 3, 0],
       [0, 1, 6, 5]])

In [40]:
np.power(arr1,arr2)

array([[      256,      1024,        16,    117649],
       [    32768,      6561,        81, 387420489],
       [        8,         1,    279936,     15625]])

In [41]:
np.sqrt(arr1)

array([[1.41421356, 2.        , 1.41421356, 2.64575131],
       [2.82842712, 3.        , 1.73205081, 3.        ],
       [2.82842712, 1.        , 2.44948974, 2.23606798]])

In [42]:
# numpy ----statistical function
arr1

array([[2, 4, 2, 7],
       [8, 9, 3, 9],
       [8, 1, 6, 5]])

In [43]:
np.mean(arr1)

5.333333333333333

In [44]:
np.median(arr1)

5.5

In [45]:
np.std(arr1)

2.778888666755511

LECTURE4 NUMPY

In [1]:
import numpy as np

In [6]:
arr=np.array([2,3,4,15,34,43,43,6])

In [7]:
arr

array([ 2,  3,  4, 15, 34, 43, 43,  6])

In [8]:
np.sort(arr) # arrange in ascending order

array([ 2,  3,  4,  6, 15, 34, 43, 43])

In [10]:
np.searchsorted(arr,7)  #  to maintain the ascending order where this particular number is placed

3

In [12]:
arr1=np.array([0,34,344,3432,876,9890])

In [13]:
np.count_nonzero(arr1)  # giving the total count of nonzero

5

In [16]:
np.where(arr1>45)  # giving the indexes of greater than 45

(array([2, 3, 4, 5]),)

In [18]:
np.extract(arr>3,arr) # extracting the conditioned data --first is condition and --other is place

array([ 4, 15, 34, 43, 43,  6])

In [19]:
arr

array([ 2,  3,  4, 15, 34, 43, 43,  6])

In [20]:
# numpy---byte swapping
arr1

array([   0,   34,  344, 3432,  876, 9890])

In [23]:
arr

array([ 2,  3,  4, 15, 34, 43, 43,  6])

In [ ]:
byteswap mode represent the their data into byte mode

In [22]:
arr.byteswap()

array([ 144115188075855872,  216172782113783808,  288230376151711744,
       1080863910568919040, 2449958197289549824, 3098476543630901248,
       3098476543630901248,  432345564227567616])

In [24]:
# numpy--copies and views
arr1

array([   0,   34,  344, 3432,  876, 9890])

In [25]:
a=np.copy(arr1)  # creating deep copy ---changes in data willl be visible in only one file .

In [26]:
a=np.copy(arr1)

In [28]:
b=arr1.view()  # trying to do swallow copy--changes in one will be reflected in other as well

In [29]:
b

array([   0,   34,  344, 3432,  876, 9890])

In [30]:
b[0]=244

In [31]:
b

array([ 244,   34,  344, 3432,  876, 9890])

In [33]:
arr1

array([ 244,   34,  344, 3432,  876, 9890])

In [34]:
# numpy ---matrix library
import numpy.matlib as nm

In [36]:
nm.zeros(5)   #creating matrices with zeros

matrix([[0., 0., 0., 0., 0.]])

In [37]:
nm.ones((3,4))  # creating matrices with ones

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
nm.eye(5)   # creating matrices with one in diagonals and others in zeros

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [39]:
# numpy--linear algebra

array([ 244,   34,  344, 3432,  876, 9890])

In [40]:
arr1=np.random.randint([[3,4],[34,22]])
arr2=np.random.randint([[56,65],[987,98]])    

In [41]:
arr1

array([[ 2,  2],
       [15,  7]])

In [42]:
arr2

array([[30,  6],
       [28, 97]])

In [43]:
np.dot(arr1,arr2)  # it is matrix multiplication b/w arr1 and arr2

array([[116, 206],
       [646, 769]])

In [44]:
arr1@arr2

array([[116, 206],
       [646, 769]])

In [ ]:
# eigen values and eigen vectors are all possible in numpy